const cartActionTypes = {
  LOADING_CART: "LOADING_CART",
  LOAD_CART: "LOAD_CART",
  INCREASE_ITEM_QUANTITY: "INCREASE_ITEM_QUANTITY",
  DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
};

export default cartActionTypes;
