const productActionTypes = {
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  LOAD_HOTTEST_PRODUCTS: "LOAD_HOTTEST_PRODUCTS",
  LOAD_LATEST_PRODUCTS: "LOAD_LATEST_PRODUCTS",
  LOADING: "LOADING",
  SOMETHING_WENT_FISHY: "SOMETHING_WENT_FISHY",
};

export default productActionTypes;
